package com.example.greenscene.ui.theme
import androidx.compose.ui.graphics.Color

val theme_light_primary = Color(0xFF00A852)
val theme_light_onPrimary = Color(0xFFFFFFFF)
val theme_light_primaryContainer = Color(0xFF77FD9B)
val theme_light_onPrimaryContainer = Color(0xFF00210B)
val theme_light_secondary = Color(0xFF506352)
val theme_light_onSecondary = Color(0xFFFFFFFF)
val theme_light_secondaryContainer = Color(0xFFD3E8D2)
val theme_light_onSecondaryContainer = Color(0xFF0E1F12)
val theme_light_tertiary = Color(0xFF39656E)
val theme_light_onTertiary = Color(0xFFFFFFFF)
val theme_light_tertiaryContainer = Color(0xFFBDEAF4)
val theme_light_onTertiaryContainer = Color(0xFF001F25)
val theme_light_error = Color(0xFFBA1A1A)
val theme_light_errorContainer = Color(0xFFFFDAD6)
val theme_light_onError = Color(0xFFFFFFFF)
val theme_light_onErrorContainer = Color(0xFF410002)
val theme_light_background = Color(0xFFFCFDF7)
val theme_light_onBackground = Color(0xFF191C19)
val theme_light_surface = Color(0xFFFCFDF7)
val theme_light_onSurface = Color(0xFF191C19)
val theme_light_surfaceVariant = Color(0xFFDDE5DA)
val theme_light_onSurfaceVariant = Color(0xFF414941)
val theme_light_outline = Color(0xFF717970)
val theme_light_inverseOnSurface = Color(0xFFF0F1EC)
val theme_light_inverseSurface = Color(0xFF2E312E)
val theme_light_inversePrimary = Color( 0xFF59DF82)
val theme_light_shadow = Color(0xFF000000)
val theme_light_surfaceTint = Color(0xFF006D33)
val theme_light_outlineVariant = Color(0xFFC1C9BE)
val theme_light_scrim = Color(0xFF000000)

val theme_dark_primary = Color(0xFF59DF82)
val theme_dark_onPrimary = Color(0xFF003917)
val theme_dark_primaryContainer = Color(0xFF005225)
val theme_dark_onPrimaryContainer = Color(0xFF77FD9B)
val theme_dark_secondary = Color(0xFFB7CCB7)
val theme_dark_onSecondary = Color(0xFF233425)
val theme_dark_secondaryContainer = Color(0xFF394B3B)
val theme_dark_onSecondaryContainer = Color(0xFFD3E8D2)
val theme_dark_tertiary = Color(0xFFA2CED8)
val theme_dark_onTertiary = Color(0xFF00363E)
val theme_dark_tertiaryContainer = Color(0xFF204D55)
val theme_dark_onTertiaryContainer = Color(0xFFBDEAF4)
val theme_dark_error = Color(0xFFFFB4AB)
val theme_dark_errorContainer = Color(0xFF93000A)
val theme_dark_onError = Color(0xFF690005)
val theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val theme_dark_background = Color(0xFF191C19)
val theme_dark_onBackground = Color(0xFFE2E3DE)
val theme_dark_surface = Color(0xFF191C19)
val theme_dark_onSurface = Color(0xFFE2E3DE)
val theme_dark_surfaceVariant = Color(0xFF414941)
val theme_dark_onSurfaceVariant = Color(0xFFC1C9BE)
val theme_dark_outline = Color(0xFF8B9389)
val theme_dark_inverseOnSurface = Color(0xFF191C19)
val theme_dark_inverseSurface = Color(0xFFE2E3DE)
val theme_dark_inversePrimary = Color(0xFF006D33)
val theme_dark_shadow = Color(0xFF000000)
val theme_dark_surfaceTint = Color(0xFF59DF82)
val theme_dark_outlineVariant = Color(0xFF414941)
val theme_dark_scrim = Color(0xFF000000)


val seed = Color(0xFF00A852)
